### ISSUE TITLE
fizzbuzz 만들기

### ISSUE THREAD

**Issue by sooyoung-wind** [team2-NaN/team_NaN_project#1]
## Description

 0부터 30까지의 숫자들을 fizzbuzz 개념을 사용하여 출력물을 만들어 본다.

## Tasks

- [x] 3의 배수인 숫자를 fizz로 출력한다. 
- [x] 5의 배수인 숫자를 buzz로 출력한다.
- [x] 15의 배수인 숫자를 fizzbuzz로 출력한다.

## References

- [fizzbuzz](https://en.wikipedia.org/wiki/Fizz_buzz)
